import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRoute,
  Link,
} from "@tanstack/react-router";
import { organization, jsonLdScript } from "@/lib/seo/json-ld";
import "../styles.css";

const SITE_URL = "https://example.supacode.dev";
const SITE_NAME = "SupaCode Starter";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: `${SITE_NAME} — Generated by SupaCode` },
      {
        name: "description",
        content:
          "A SupaCode-generated TanStack Start app. SSR by default. SEO and AEO baked in. Edison stands by, sir.",
      },
      { name: "theme-color", content: "#F4F4F1" },
      { property: "og:type", content: "website" },
      { property: "og:site_name", content: SITE_NAME },
      { property: "og:title", content: SITE_NAME },
      {
        property: "og:description",
        content: "Generated by SupaCode. SSR + SEO + AEO from prompt one.",
      },
      { property: "og:url", content: SITE_URL },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "robots", content: "index, follow" },
    ],
    links: [
      { rel: "icon", href: "/favicon.svg", type: "image/svg+xml" },
      { rel: "canonical", href: SITE_URL },
      // Preconnect to Google Fonts; if you self-host, remove these.
      { rel: "preconnect", href: "https://fonts.googleapis.com" },
      { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "" },
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,400;0,500;1,400;1,500&family=Inter+Tight:wght@400;500;600&family=JetBrains+Mono:wght@400;500&family=Caveat:wght@500&display=swap",
      },
    ],
    scripts: [
      jsonLdScript(
        organization({
          name: SITE_NAME,
          url: SITE_URL,
          description:
            "A SupaCode starter app — TanStack Start + SSR + Brand System v5.",
          sameAs: ["https://supacode.dev"],
        }),
      ),
    ],
  }),
  component: RootLayout,
  notFoundComponent: NotFound,
  errorComponent: RootError,
});

function RootLayout() {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <a
          href="#main"
          className="absolute left-2 top-2 -translate-y-16 bg-[var(--color-ink)] px-3 py-2 text-sm text-[var(--color-paper)] focus:translate-y-0"
        >
          Skip to content
        </a>

        <header className="border-b border-[var(--color-ink)]">
          <nav
            aria-label="Primary"
            className="mx-auto flex max-w-5xl items-baseline justify-between px-6 py-4"
          >
            <Link
              to="/"
              className="font-display text-xl italic font-medium text-[var(--color-ink)]"
            >
              SupaCode
            </Link>
            <ul className="flex gap-6 font-mono text-xs uppercase tracking-widest text-[var(--color-mute)]">
              <li>
                <Link to="/" className="hover:text-[var(--color-coral)]">
                  Home
                </Link>
              </li>
              <li>
                <Link to="/about" className="hover:text-[var(--color-coral)]">
                  About
                </Link>
              </li>
              <li>
                <a
                  href="https://supacode.dev/discoverability"
                  className="hover:text-[var(--color-coral)]"
                >
                  Discoverability
                </a>
              </li>
            </ul>
          </nav>
        </header>

        <main id="main" className="mx-auto max-w-5xl px-6 py-12">
          <Outlet />
        </main>

        <footer className="border-t border-[var(--color-ink)] mt-16">
          <div className="mx-auto max-w-5xl px-6 py-6 font-mono text-xs uppercase tracking-widest text-[var(--color-mute)] flex flex-wrap justify-between gap-2">
            <span>
              Generated by <strong className="text-[var(--color-ink)]">SupaCode</strong>
            </span>
            <span>Brand System v5 · editorial mode</span>
          </div>
        </footer>

        <Scripts />
      </body>
    </html>
  );
}

function NotFound() {
  return (
    <section className="prose-on-cream py-16">
      <p className="font-mono text-xs uppercase tracking-widest text-[var(--color-coral)] mb-4">
        404 · off the runway
      </p>
      <h1 className="text-5xl italic font-medium mb-4">That page never existed, sir.</h1>
      <p className="text-[var(--color-ink-soft)] max-w-prose mb-6">
        Or it did, briefly, and has since flown elsewhere. Either way, the simplest
        course is to return to known altitude.
      </p>
      <Link to="/" className="text-[var(--color-coral-deep)] underline underline-offset-4">
        Return home →
      </Link>
    </section>
  );
}

function RootError({ error }: { error: Error }) {
  return (
    <section className="py-16">
      <p className="font-mono text-xs uppercase tracking-widest text-[var(--color-coral)] mb-4">
        Unscheduled descent
      </p>
      <h1 className="text-5xl italic font-medium mb-4">Something went sideways.</h1>
      <p className="text-[var(--color-ink-soft)] max-w-prose mb-6">
        Aviation visibility check, sir — we caught the error before it reached the
        ground. The engineering crew has been notified.
      </p>
      <pre className="font-mono text-xs bg-[var(--color-paper-deep)] border border-[var(--color-cream-deep)] p-4 overflow-x-auto">
        {error.message}
      </pre>
      <Link
        to="/"
        className="inline-block mt-6 text-[var(--color-coral-deep)] underline underline-offset-4"
      >
        Return home →
      </Link>
    </section>
  );
}
